name: Build docker images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Extract tag name
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Build with tag version
        run: |
            docker build -t bot:${{ env.VERSION }} .
            docker tag bot:${{ env.VERSION }} ghcr.io/${{ env.REPO }}:${{ env.VERSION }}
            docker push ghcr.io/${{ env.REPO }}:${{ env.VERSION }}

      # Conditionally tag and push docker image as latest, unless tag name contains '-dev'
      - name: Tag and push docker image as latest
        if: contains(env.VERSION, '-dev') == false
        run: |
            docker tag bot:${{ env.VERSION }} ghcr.io/${{ env.REPO }}:latest
            docker push ghcr.io/${{ env.REPO }}:latest